# apps/tickets/services.py
import logging
from django.db import transaction
from django.utils import timezone

from apps.orders.models import Order, OrderItem
from .models import Ticket
from .qr import QRCodeGenerator

logger = logging.getLogger(__name__)


class TicketService:
    """
    Handles all ticket lifecycle operations.

    Called by:
    - Payment callback (Phase 6) after confirmed payment
    - Admin endpoint for manual ticket regeneration
    - Management command for bulk operations
    """

    @staticmethod
    @transaction.atomic
    def generate_tickets_for_order(order: Order) -> list:
        """
        Generate one Ticket (+ QR code) per seat in the order.

        Example:
          OrderItem: 3x Regular → creates 3 Ticket rows
          OrderItem: 1x VIP    → creates 1 Ticket row
          Total: 4 tickets, 4 QR codes, all unique

        IDEMPOTENCY:
        If called twice (e.g. duplicate callback), we check if
        tickets already exist for this order and skip gracefully.
        This is critical — we must never double-issue tickets.

        Args:
            order: A CONFIRMED Order instance

        Returns:
            List of generated Ticket instances
        """

        # ── Guard: only generate for confirmed orders ──────────────────
        if order.status != Order.Status.CONFIRMED:
            raise ValueError(
                f"Cannot generate tickets for order with status: {order.status}. "
                f"Order must be confirmed."
            )

        # ── Idempotency check: tickets already generated? ───────────────
        existing_tickets = Ticket.objects.filter(order=order)
        if existing_tickets.exists():
            logger.warning(
                f"[Tixora-Tickets] Tickets already exist for order "
                f"{order.reference} — skipping generation. "
                f"Existing count: {existing_tickets.count()}"
            )
            return list(existing_tickets)

        # ── Generate tickets for each line item ─────────────────────────
        all_tickets = []
        items       = order.items.select_related(
                        'ticket_type__event'
                      ).all()

        for item in items:
            item_tickets = TicketService._generate_for_item(order, item)
            all_tickets.extend(item_tickets)

        logger.info(
            f"[Tixora-Tickets] Generated {len(all_tickets)} ticket(s) "
            f"for order {order.reference}"
        )

        return all_tickets

    @staticmethod
    def _generate_for_item(order: Order, item: OrderItem) -> list:
        """
        Generate `item.quantity` tickets for a single OrderItem.
        Each ticket gets its own UUID and QR code.
        """
        tickets = []

        for seat_number in range(item.quantity):
            try:
                ticket = TicketService._create_single_ticket(order, item)
                tickets.append(ticket)
                logger.debug(
                    f"[Tixora-Tickets] Created ticket {ticket.ticket_uuid} "
                    f"({seat_number + 1}/{item.quantity}) for "
                    f"{item.ticket_type.name}"
                )
            except Exception as e:
                logger.error(
                    f"[Tixora-Tickets] Failed to create ticket "
                    f"{seat_number + 1} for item {item.id}: {e}",
                    exc_info=True
                )
                raise  # Re-raise — transaction.atomic will roll back all

        return tickets

    @staticmethod
    def _create_single_ticket(order: Order, item: OrderItem) -> Ticket:
        """
        Create one Ticket and generate its QR code.

        Steps:
        1. Create the Ticket row (gets a UUID automatically)
        2. Generate QR code from the UUID
        3. Save the QR image to the ticket's ImageField
        """

        # Step 1: Create ticket (UUID auto-generated by model default)
        ticket = Ticket.objects.create(
            order       = order,
            order_item  = item,
            ticket_type = item.ticket_type,
            owner       = order.customer,
            status      = Ticket.Status.ACTIVE,
        )

        # Step 2: Generate QR from the ticket's UUID
        qr_image = QRCodeGenerator.generate(ticket.ticket_uuid)

        # Step 3: Save QR image to the ticket
        # Django's ImageField handles the file storage
        # Path will be: media/tickets/qr_codes/ticket_<uuid>.png
        ticket.qr_code.save(
            qr_image.name,
            qr_image,
            save=True       # Triggers a DB save after file write
        )

        return ticket

    @staticmethod
    def get_ticket_for_validation(ticket_uuid: str) -> Ticket:
        """
        Fetch a ticket by UUID for check-in validation.
        Used by the scanner in Phase 9.

        Returns the ticket with related data pre-loaded.
        Raises Ticket.DoesNotExist if UUID not found.
        """
        return Ticket.objects.select_related(
            'order',
            'ticket_type__event',
            'owner',
        ).get(ticket_uuid=ticket_uuid)

    @staticmethod
    @transaction.atomic
    def cancel_tickets_for_order(order: Order) -> int:
        """
        Cancel all tickets for a refunded/cancelled order.
        Returns count of cancelled tickets.
        """
        count = Ticket.objects.filter(
            order=order,
            status=Ticket.Status.ACTIVE
        ).update(status=Ticket.Status.CANCELLED)

        logger.info(
            f"[Tixora-Tickets] Cancelled {count} ticket(s) "
            f"for order {order.reference}"
        )
        return count