# Generated by Django 6.0.4 on 2026-04-23 13:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scanned_uuid', models.CharField(max_length=100)),
                ('result', models.CharField(choices=[('success', 'Success'), ('already_used', 'Already Used'), ('invalid_ticket', 'Invalid Ticket'), ('wrong_event', 'Wrong Event'), ('expired', 'Expired'), ('cancelled', 'Ticket Cancelled')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkins_performed', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkins', to='tickets.ticket')),
            ],
            options={
                'db_table': 'tixora_checkins',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
